# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-05 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
        ('water', '0001_initial'),
        ('pko', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pko',
            name='counter_e',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='counter.CounterE', verbose_name='Оплачиваемый счетчик электричества'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pko',
            name='counter_w',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='water.CounterW', verbose_name='Оплачиваемый счетчик воды'),
            preserve_default=False,
        ),
    ]
