# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-05 19:14
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+999999999'. Разрешено до 15 символов.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
