version: '2'

volumes:
  postgres_data_local: {}
  postgres_backup_local: {}

services:
  postgres:
    image: postgres:alpine
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
      - postgres_backup_local:/backups
    environment:
      - POSTGRES_USER=sun
      - POSTGRES_PASSWORD=goodleon69
    ports:
      - "5432:5432"

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"

  adminer:
    image: adminer
    ports:
      - 8080:8080
    links:
      - postgres


  redis:
    image: redis:3.0
