# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-04 17:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Homes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=100, verbose_name='Комментарий (100 символов)')),
                ('street', models.CharField(blank=True, max_length=150, verbose_name='Улица')),
                ('numhome', models.IntegerField(blank=True, default=0, verbose_name='Номер дома')),
                ('section', models.IntegerField(blank=True, default=0, verbose_name='Номер участка')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец участка')),
            ],
            options={
                'verbose_name_plural': 'Участки',
                'ordering': ['-section'],
                'verbose_name': 'Участки',
            },
        ),
    ]
