# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-04 19:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homes', '0003_auto_20180104_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('month', models.CharField(choices=[('Январь', 'Январь'), ('Февраль', 'Февраль'), ('Март', 'Март'), ('Апрель', 'Апрель'), ('Май', 'Май'), ('Июнь', 'Июнь'), ('Июль', 'Июль'), ('Август', 'Август'), ('Сентябрь', 'Сентябрь'), ('Октябрь', 'Октябрь'), ('Ноябрь', 'Ноябрь'), ('Декабрь', 'Декабрь')], default='Январь', max_length=8, verbose_name='Месяц снятия показаний')),
                ('year', models.CharField(choices=[('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020')], default='2018', max_length=4, verbose_name='Год снятия показаний')),
                ('comment', models.CharField(blank=True, max_length=100, verbose_name='Комментарий (100 символов)')),
                ('indication_day', models.FloatField(verbose_name='Показание дневной тариф')),
                ('indication_night', models.FloatField(verbose_name='Показание ночной тариф')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор документа')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homes.Homes', verbose_name='Участок')),
            ],
            options={
                'verbose_name_plural': 'Счетчики электроэнергии индивидуальные',
                'verbose_name': 'Счетчик электроэнергии индивидуальный',
                'ordering': ['-month', 'year', 'autor'],
            },
        ),
    ]
